package com.junk.application.discordfeedhub.panel;

import com.junk.application.discordfeedhub.utils.Utility;
import java.awt.Desktop;
import java.io.IOException;
import java.io.InputStream;
import java.net.URI;
import java.nio.charset.StandardCharsets;
import java.util.Properties;
import java.util.Scanner;

/**
 *
 * @author elmerhd
 */
public class AboutPanel extends javax.swing.JPanel {

    /**
     * Creates new form AboutPanel
     */
    public AboutPanel() throws IOException {
        initComponents();
        setupInfo();
    }
    
    public void setupInfo() throws IOException {
        String htmlContent = loadHtmlContent();
        editorPaneInfo.setText(htmlContent);
        editorPaneInfo.setCaretPosition(0);

        editorPaneInfo.addHyperlinkListener(e -> {
            if (e.getEventType() == javax.swing.event.HyperlinkEvent.EventType.ACTIVATED) {
                try {
                    Desktop.getDesktop().browse(new URI(e.getURL().toString()));
                } catch (Exception ex) {
                    ex.printStackTrace();
                }
            }
        });
    }
    
    private String loadHtmlContent() throws IOException {
        String html = "";
        Properties applicationProperty = Utility.getApplicationProperty();
        try (InputStream is = getClass().getResourceAsStream(Utility.getAboutInfoHTMLFile());
            Scanner scanner = new Scanner(is, StandardCharsets.UTF_8.name())) {
            html = scanner.useDelimiter("\\A").next();
        } catch (IOException ex) {
            html = "<html><body><p>Error loading About content.</p></body></html>";
            System.getLogger(AboutPanel.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }

        // Replace placeholders with actual system info
        String javaVersion = System.getProperty("java.version") + " (" + System.getProperty("java.vm.name") + ")";
        String osInfo = System.getProperty("os.name") + " (" + System.getProperty("os.version") + ") on " + System.getProperty("os.arch");
        String appVersion = applicationProperty.getProperty("app.version");
        html = html.replace("${appVersion}", appVersion)
                   .replace("${javaVersion}", javaVersion)
                   .replace("${osInfo}", osInfo)
                   .replace("${userDir}", Utility.getApplicationFolder());
        
        return html;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPaneInfo = new javax.swing.JScrollPane();
        editorPaneInfo = new javax.swing.JEditorPane();
        labelLogo = new javax.swing.JLabel();

        editorPaneInfo.setEditable(false);
        editorPaneInfo.setContentType("text/html"); // NOI18N
        editorPaneInfo.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        scrollPaneInfo.setViewportView(editorPaneInfo);

        labelLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/junk/application/discordfeedhub/logo-256.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPaneInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE)
                    .addComponent(labelLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(scrollPaneInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane editorPaneInfo;
    private javax.swing.JLabel labelLogo;
    private javax.swing.JScrollPane scrollPaneInfo;
    // End of variables declaration//GEN-END:variables
}
