package com.junk.application.discordfeedhub.panel;

import com.junk.application.discordfeedhub.utils.DatabaseManager;
import com.junk.application.discordfeedhub.utils.ExtendedDialog;
import com.junk.application.discordfeedhub.utils.HeaderRenderer;
import com.junk.application.discordfeedhub.utils.RssSourceTableModel;
import com.junk.application.discordfeedhub.utils.Utility;
import java.awt.ComponentOrientation;
import java.awt.Dimension;
import java.io.IOException;
import java.sql.SQLException;
import javax.swing.Box;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author elmerhd
 */
public class DataPanel extends javax.swing.JPanel {
    
    private JFrame parent = null;
    private RssSourceTableModel model = new RssSourceTableModel();
    private String statusText = "Idle";
    
    /**
     * Creates new form DataPanel
     */
    public DataPanel(JFrame frame) throws SQLException, IOException {
        initComponents();
        this.parent = frame;
        initComponentsVisual();
        loadSources();
        checkRunningScheduler();
    }
    
    public String getStatusText() {
        return statusText;
    }
    
    public void setStatusText(String text) {
        this.statusText = text;
    }
    
    public void initComponentsVisual() {
        TableColumnModel cm = dataTable.getColumnModel();

        // Fix first column
        cm.getColumn(0).setPreferredWidth(50);
        cm.getColumn(0).setMinWidth(50);
        cm.getColumn(0).setMaxWidth(50);
        
        cm.getColumn(5).setPreferredWidth(100);
        cm.getColumn(5).setMinWidth(100);
        cm.getColumn(5).setMaxWidth(100);
        
        dataTable.setAutoResizeMode(JTable.AUTO_RESIZE_SUBSEQUENT_COLUMNS);
        
        dataTable.getTableHeader().setDefaultRenderer(new HeaderRenderer());
        
    }
    
    public void loadSources() throws SQLException, IOException {
        model.setData(DatabaseManager.loadSources());
    }
    
    public void checkRunningScheduler() {
        toggleButtonRun.setText(getRunButtonText());
        toggleButtonRun.setSelected(Utility.getScheduler().isStarted());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPaneTable = new javax.swing.JScrollPane();
        dataTable = new javax.swing.JTable();
        panelToolbar = new javax.swing.JPanel();
        buttonUpdate = new javax.swing.JButton();
        buttonNew = new javax.swing.JButton();
        toggleButtonRun = new javax.swing.JToggleButton();
        labelStatus = new javax.swing.JLabel();

        dataTable.setModel(model);
        dataTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        scrollPaneTable.setViewportView(dataTable);

        panelToolbar.setLayout(new javax.swing.BoxLayout(panelToolbar, javax.swing.BoxLayout.LINE_AXIS));

        buttonUpdate.setIcon(Utility.getUpdateIcon());
        buttonUpdate.setText("Update");
        buttonUpdate.addActionListener(this::buttonUpdateActionPerformed);
        panelToolbar.add(buttonUpdate);
        panelToolbar.add(Box.createRigidArea(new Dimension(5, 0)));

        buttonNew.setIcon(Utility.getNewIcon());
        buttonNew.setMnemonic('N');
        buttonNew.setText("New");
        buttonNew.addActionListener(this::buttonNewActionPerformed);
        panelToolbar.add(buttonNew);
        panelToolbar.add(Box.createRigidArea(new Dimension(5, 0)));

        toggleButtonRun.setText(getRunButtonText());
        toggleButtonRun.addActionListener(this::toggleButtonRunActionPerformed);
        panelToolbar.add(toggleButtonRun);

        labelStatus.setText(getStatusText());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(scrollPaneTable, javax.swing.GroupLayout.DEFAULT_SIZE, 784, Short.MAX_VALUE)
                .addGap(5, 5, 5))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelToolbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(panelToolbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(scrollPaneTable, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                .addGap(10, 10, 10)
                .addComponent(labelStatus)
                .addGap(10, 10, 10))
        );

        panelToolbar.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNewActionPerformed
        ExtendedDialog extendedDialog = new ExtendedDialog(parent, "New RSS Resource", new ResourcePanel(this));
        extendedDialog.setVisible(true);
    }//GEN-LAST:event_buttonNewActionPerformed

    private void buttonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUpdateActionPerformed
        try {
            int row = dataTable.getSelectedRow();
            int id = (int) dataTable.getValueAt(row, 0);
            ExtendedDialog extendedDialog = new ExtendedDialog(parent, "Update RSS Resource", new ResourcePanel(this, true, id));
            extendedDialog.setVisible(true);
        } catch (IndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(this, "Select a row from the table!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_buttonUpdateActionPerformed

    private void toggleButtonRunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleButtonRunActionPerformed
        if (model.getRowCount() < 1) {
            JOptionPane.showMessageDialog(this, "No RSS Resource!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (Utility.getScheduler().isStarted()) {
            Utility.getScheduler().shutdown(labelStatus);
        } else {
            Utility.getScheduler().start(labelStatus);
        }
        toggleButtonRun.setText(getRunButtonText());
    }//GEN-LAST:event_toggleButtonRunActionPerformed
    
    public String getRunButtonText() {
        if (Utility.getScheduler().isStarted()) {
            toggleButtonRun.setIcon(Utility.getStopIcon());
        } else {
            toggleButtonRun.setIcon(Utility.getStartIcon());
        }
        return Utility.getScheduler().isStarted() ? "Stop" : "Start";
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonNew;
    private javax.swing.JButton buttonUpdate;
    private javax.swing.JTable dataTable;
    private javax.swing.JLabel labelStatus;
    private javax.swing.JPanel panelToolbar;
    private javax.swing.JScrollPane scrollPaneTable;
    private javax.swing.JToggleButton toggleButtonRun;
    // End of variables declaration//GEN-END:variables
}
