package com.junk.application.discordfeedhub.panel;

import com.junk.application.discordfeedhub.utils.DatabaseManager;
import com.junk.application.discordfeedhub.utils.ExtendedDialog;
import com.junk.application.discordfeedhub.utils.RssSourceTableModel;
import com.junk.application.discordfeedhub.utils.DatabaseStatementStatus;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.JTableHeader;

/**
 *
 * @author elmerhd
 */
public class DataPanel extends javax.swing.JPanel {
    
    private JFrame parent = null;
    private RssSourceTableModel model = new RssSourceTableModel();
    private String statusText = "Idle";
    
    /**
     * Creates new form DataPanel
     */
    public DataPanel(JFrame frame) {
        initComponents();
        this.parent = frame;
        initComponentsVisual();
        loadSources();
    }
    
    public String getStatusText() {
        return statusText;
    }
    
    public void setStatusText(String text) {
        this.statusText = text;
    }
    
    public void initComponentsVisual() {
        JTableHeader header = dataTable.getTableHeader();
        header.setFont(dataTable.getFont());
    }
    
    public void loadSources() {
        model.setData(DatabaseManager.loadSources());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonUpdate = new javax.swing.JButton();
        buttonNew = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        dataTable = new javax.swing.JTable();
        labelStatus = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        buttonDelete = new javax.swing.JButton();

        buttonUpdate.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        buttonUpdate.setText("Update");
        buttonUpdate.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        buttonUpdate.addActionListener(this::buttonUpdateActionPerformed);

        buttonNew.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        buttonNew.setText("New");
        buttonNew.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        buttonNew.addActionListener(this::buttonNewActionPerformed);

        dataTable.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        dataTable.setModel(model);
        dataTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(dataTable);

        labelStatus.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        labelStatus.setText(getStatusText());

        jButton3.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jButton3.setText("Run");

        buttonDelete.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        buttonDelete.setText("Delete");
        buttonDelete.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        buttonDelete.addActionListener(this::buttonDeleteActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 256, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addGap(10, 10, 10)
                        .addComponent(buttonNew, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(buttonUpdate)
                        .addGap(10, 10, 10)
                        .addComponent(buttonDelete))
                    .addComponent(labelStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {buttonDelete, buttonNew, buttonUpdate, jButton3});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(buttonDelete)
                    .addComponent(buttonNew)
                    .addComponent(buttonUpdate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                .addGap(10, 10, 10)
                .addComponent(labelStatus)
                .addGap(10, 10, 10))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {buttonDelete, buttonNew, buttonUpdate, jButton3});

    }// </editor-fold>//GEN-END:initComponents

    private void buttonNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNewActionPerformed
        ExtendedDialog extendedDialog = new ExtendedDialog(parent, "New RSS Resource", new ResourcePanel(this));
        extendedDialog.setVisible(true);
    }//GEN-LAST:event_buttonNewActionPerformed

    private void buttonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUpdateActionPerformed
        try {
            int row = dataTable.getSelectedRow();
            int id = (int) dataTable.getValueAt(row, 0);
            ExtendedDialog extendedDialog = new ExtendedDialog(parent, "Update RSS Resource", new ResourcePanel(this, true, id));
            extendedDialog.setVisible(true);
        } catch (IndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(this, "Select a row from the table!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_buttonUpdateActionPerformed

    private void buttonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteActionPerformed
        try {
            int row = dataTable.getSelectedRow();
            int id = (int) dataTable.getValueAt(row, 0);
            String title = (String) dataTable.getValueAt(row, 1);
            int option = JOptionPane.showConfirmDialog(this, "Sure to delete " + title + "?", "Confirmation", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (option == JOptionPane.YES_OPTION) {
                DatabaseStatementStatus status = DatabaseManager.deleteRssSource(id);
                loadSources();
            } 
        } catch (IndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(this, "Select a row from the table!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_buttonDeleteActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonDelete;
    private javax.swing.JButton buttonNew;
    private javax.swing.JButton buttonUpdate;
    private javax.swing.JTable dataTable;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelStatus;
    // End of variables declaration//GEN-END:variables
}
