package com.junk.application.discordfeedhub.panel;

import com.junk.application.discordfeedhub.utils.DatabaseManager;
import com.junk.application.discordfeedhub.utils.ExtendedDialog;
import com.junk.application.discordfeedhub.utils.RssSourceTableModel;
import com.junk.application.discordfeedhub.utils.DmlResult;
import com.junk.application.discordfeedhub.utils.Utility;
import java.awt.ComponentOrientation;
import java.awt.Dimension;
import java.io.IOException;
import java.sql.SQLException;
import javax.swing.Box;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.JTableHeader;

/**
 *
 * @author elmerhd
 */
public class DataPanel extends javax.swing.JPanel {
    
    private JFrame parent = null;
    private RssSourceTableModel model = new RssSourceTableModel();
    private String statusText = "Idle";
    
    /**
     * Creates new form DataPanel
     */
    public DataPanel(JFrame frame) throws SQLException, IOException {
        initComponents();
        this.parent = frame;
        initComponentsVisual();
        loadSources();
        buttonRun.setText(getRunButtonText());
    }
    
    public String getStatusText() {
        return statusText;
    }
    
    public void setStatusText(String text) {
        this.statusText = text;
    }
    
    public void initComponentsVisual() {
        JTableHeader header = dataTable.getTableHeader();
        header.setFont(dataTable.getFont());
    }
    
    public void loadSources() throws SQLException, IOException {
        model.setData(DatabaseManager.loadSources());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPaneTable = new javax.swing.JScrollPane();
        dataTable = new javax.swing.JTable();
        labelStatus = new javax.swing.JLabel();
        panelToolbar = new javax.swing.JPanel();
        buttonDelete = new javax.swing.JButton();
        buttonUpdate = new javax.swing.JButton();
        buttonNew = new javax.swing.JButton();
        buttonRun = new javax.swing.JButton();

        dataTable.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        dataTable.setModel(model);
        dataTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        scrollPaneTable.setViewportView(dataTable);

        labelStatus.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        labelStatus.setText(getStatusText());

        panelToolbar.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        panelToolbar.setLayout(new javax.swing.BoxLayout(panelToolbar, javax.swing.BoxLayout.LINE_AXIS));

        buttonDelete.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        buttonDelete.setText("Delete");
        buttonDelete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonDelete.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        buttonDelete.addActionListener(this::buttonDeleteActionPerformed);
        panelToolbar.add(buttonDelete);
        panelToolbar.add(Box.createRigidArea(new Dimension(5, 0)));

        buttonUpdate.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        buttonUpdate.setText("Update");
        buttonUpdate.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonUpdate.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        buttonUpdate.addActionListener(this::buttonUpdateActionPerformed);
        panelToolbar.add(buttonUpdate);
        panelToolbar.add(Box.createRigidArea(new Dimension(5, 0)));

        buttonNew.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        buttonNew.setText("New");
        buttonNew.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonNew.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        buttonNew.addActionListener(this::buttonNewActionPerformed);
        panelToolbar.add(buttonNew);
        panelToolbar.add(Box.createRigidArea(new Dimension(5, 0)));

        buttonRun.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        buttonRun.setText(getRunButtonText());
        buttonRun.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonRun.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        buttonRun.addActionListener(this::buttonRunActionPerformed);
        panelToolbar.add(buttonRun);
        panelToolbar.add(Box.createRigidArea(new Dimension(5, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPaneTable, javax.swing.GroupLayout.DEFAULT_SIZE, 784, Short.MAX_VALUE)
                    .addComponent(labelStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(5, 5, 5))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelToolbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(panelToolbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPaneTable, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                .addGap(5, 5, 5)
                .addComponent(labelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );

        panelToolbar.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNewActionPerformed
        ExtendedDialog extendedDialog = new ExtendedDialog(parent, "New RSS Resource", new ResourcePanel(this));
        extendedDialog.setVisible(true);
    }//GEN-LAST:event_buttonNewActionPerformed

    private void buttonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUpdateActionPerformed
        try {
            int row = dataTable.getSelectedRow();
            int id = (int) dataTable.getValueAt(row, 0);
            ExtendedDialog extendedDialog = new ExtendedDialog(parent, "Update RSS Resource", new ResourcePanel(this, true, id));
            extendedDialog.setVisible(true);
        } catch (IndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(this, "Select a row from the table!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_buttonUpdateActionPerformed

    private void buttonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteActionPerformed
        try {
            int row = dataTable.getSelectedRow();
            int id = (int) dataTable.getValueAt(row, 0);
            String title = (String) dataTable.getValueAt(row, 1);
            int option = JOptionPane.showConfirmDialog(this, "Sure to delete " + title + "?", "Confirmation", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (option == JOptionPane.YES_OPTION) {
                DmlResult dmlResult = DatabaseManager.deleteRssSource(id);
                loadSources();
            }
        } catch (IndexOutOfBoundsException ex) {
            System.getLogger(DataPanel.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            JOptionPane.showMessageDialog(this, "Select a row from the table!", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException | IOException ex) {
            System.getLogger(DataPanel.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            JOptionPane.showMessageDialog(this, "Unknown Error!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_buttonDeleteActionPerformed

    private void buttonRunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRunActionPerformed
        if (model.getRowCount() < 1) {
            JOptionPane.showMessageDialog(this, "No RSS Resource!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (Utility.getScheduler().isStarted()) {
            Utility.getScheduler().shutdown(labelStatus);
        } else {
            Utility.getScheduler().start(labelStatus);
        }
        buttonRun.setText(getRunButtonText());
    }//GEN-LAST:event_buttonRunActionPerformed
    
    public String getRunButtonText() {
        return Utility.getScheduler().isStarted() ? "Stop" : "Start";
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonDelete;
    private javax.swing.JButton buttonNew;
    private javax.swing.JButton buttonRun;
    private javax.swing.JButton buttonUpdate;
    private javax.swing.JTable dataTable;
    private javax.swing.JLabel labelStatus;
    private javax.swing.JPanel panelToolbar;
    private javax.swing.JScrollPane scrollPaneTable;
    // End of variables declaration//GEN-END:variables
}
