package com.junk.application.discordfeedhub.panel;

import aurelienribon.tweenengine.BaseTween;
import aurelienribon.tweenengine.Timeline;
import aurelienribon.tweenengine.Tween;
import aurelienribon.tweenengine.TweenCallback;
import aurelienribon.tweenengine.equations.Bounce;
import com.junk.application.discordfeedhub.ui.Main;
import com.junk.application.discordfeedhub.utils.ComponentAccessor;
import com.junk.application.discordfeedhub.utils.TweenAnimationManager;
import java.awt.Dimension;
import javax.swing.JPanel;

/**
 *
 * @author elmerhd
 */
public class LoadingPanel extends javax.swing.JPanel {
    
    private JPanel parentPanel;
    private Main mainUI;
    
    /**
     * Creates new form LoadingPanel
     */
    public LoadingPanel(Main mainUI) {
        initComponents();
        this.mainUI = mainUI;
        this.parentPanel = mainUI.mainPanel;
        initComponentsPosition();
        initializedAnimations();
    }
    
    public void initComponentsPosition() {
        this.setPreferredSize(parentPanel.getPreferredSize());
        labelAppLogo.setPreferredSize(new Dimension(256, 256));
    }
    
    public void initializedAnimations() {
        
        float appLogoCenterX = (float) ((this.parentPanel.getWidth() / 2) - (labelAppLogo.getPreferredSize().getWidth() / 2) ) ;
        float appLogoCenterY = (float) ((this.parentPanel.getHeight() / 2) - (labelAppLogo.getPreferredSize().getHeight() / 2));
        
        TweenCallback animationDone = new TweenCallback() {
            @Override
            public void onEvent(int i, BaseTween<?> bt) {
                mainUI.showDataPanel();
            }
        };
        
        Timeline.createSequence()
            .beginParallel()
                .push(Tween.set(labelAppLogo, ComponentAccessor.POSITION_X).target(appLogoCenterX))
            .end()
            .delay(2)
            // Fast drop
            .push(Tween.to(labelAppLogo, ComponentAccessor.POSITION_XY, 1.5f)
                .target(appLogoCenterX, appLogoCenterY)
                .ease(Bounce.OUT))
            .setCallback(animationDone)
            .start(TweenAnimationManager.getTweenManager());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelAppLogo = new javax.swing.JLabel();

        setLayout(null);

        labelAppLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelAppLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/junk/application/discordfeedhub/logo-256.png"))); // NOI18N
        labelAppLogo.setPreferredSize(new java.awt.Dimension(128, 128));
        add(labelAppLogo);
        labelAppLogo.setBounds(5, -500, 256, 256);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelAppLogo;
    // End of variables declaration//GEN-END:variables
}
