package com.junk.application.discordfeedhub.panel;

import com.junk.application.discordfeedhub.utils.DiscordFeedHubLogger;
import com.junk.application.discordfeedhub.utils.ExtendedPanel;
import com.junk.application.discordfeedhub.utils.NumericDocumentFilter;
import com.junk.application.discordfeedhub.utils.Preference;
import com.junk.application.discordfeedhub.utils.StartupHelper;
import com.junk.application.discordfeedhub.utils.Theme;
import com.junk.application.discordfeedhub.utils.Utility;
import java.awt.GraphicsEnvironment;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import javax.swing.DefaultComboBoxModel;
import javax.swing.SpinnerNumberModel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.text.AbstractDocument;

/**
 *
 * @author elmerhd
 */
public class PreferencePanel extends ExtendedPanel {
    
    private File preferenceFile;
    /**
     * Creates new form PreferencePanel
     */
    public PreferencePanel() {
        super();
    }
    
    @Override
    public void onInitializedPanel() {
        DiscordFeedHubLogger.getLogger(PreferencePanel.class.getName()).log(Level.INFO, "Initializing Components");
        initComponents();
        this.preferenceFile = Utility.getPreference().getFile();
    }
    
    public DefaultComboBoxModel<Theme> getThemeModel() {
        List<Theme> themes = new ArrayList<>();
        UIManager.LookAndFeelInfo[] lookAndFeels = UIManager.getInstalledLookAndFeels();
        for (UIManager.LookAndFeelInfo lookAndFeel : lookAndFeels) {
            String name = lookAndFeel.getName();
            String className = lookAndFeel.getClassName();
            themes.add(new Theme(name, className));
        }
        Theme [] list = themes.toArray(new Theme[themes.size()]);
        DefaultComboBoxModel<Theme> comboBoxModelThemes = new DefaultComboBoxModel<>(list);
        for (Theme theme : themes) {
            if (Utility.getPreference().getTheme().getClassName().equals(theme.getClassName())) {
                comboBoxModelThemes.setSelectedItem(theme);
                break;
            }
        }
        return comboBoxModelThemes;
    }
    
    public SpinnerNumberModel getFontSizeModel() {
        int fontSize = Utility.getPreference().getFontSize();
        return new SpinnerNumberModel(
            fontSize,   // initial value
            10,  // min
            30,  // max
            1    // step
        );
    }
    
    public DefaultComboBoxModel<String> getFontModel() {
        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        String[] fontFamilies = ge.getAvailableFontFamilyNames();
        DefaultComboBoxModel comboBoxModelFonts = new DefaultComboBoxModel<>(fontFamilies);
        comboBoxModelFonts.setSelectedItem(Utility.getPreference().getFontName());
        return comboBoxModelFonts;
    }
    
    public void saveSettings() throws IOException, ClassNotFoundException, InstantiationException, IllegalAccessException, UnsupportedLookAndFeelException {
        DiscordFeedHubLogger.getLogger(PreferencePanel.class.getName()).log(Level.INFO, "Saving preferences");
        Theme selectedTheme = (Theme)comboBoxThemes.getSelectedItem();
        Preference pref = new Preference(preferenceFile);
        pref.setTheme(selectedTheme);
        pref.setFontName(comboBoxFont.getSelectedItem().toString());
        pref.setFontSize((Integer) spinnerFontSize.getValue());
        pref.setSchedulerTimerInterval(Integer.valueOf(textFieldSchedulerInterval.getText()));
        pref.setWebhookQueueDelay(Integer.valueOf(textFieldWebhookDelay.getText()));
        pref.setRunningAtStartup(checkboxRunStartup.isSelected());
        pref.savePreference();
        Utility.setPreference(pref);
        DiscordFeedHubLogger.getLogger(PreferencePanel.class.getName()).log(Level.INFO, "Preferences saved");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelScheduleInterval = new javax.swing.JLabel();
        textFieldSchedulerInterval = new javax.swing.JTextField();
        labelWebhookTimer = new javax.swing.JLabel();
        textFieldWebhookDelay = new javax.swing.JTextField();
        labelTheme = new javax.swing.JLabel();
        comboBoxThemes = new javax.swing.JComboBox<>();
        labeFontName = new javax.swing.JLabel();
        comboBoxFont = new javax.swing.JComboBox<>();
        labelFontSize = new javax.swing.JLabel();
        spinnerFontSize = new javax.swing.JSpinner();
        buttonClose = new javax.swing.JButton();
        checkboxRunStartup = new javax.swing.JCheckBox();
        labelRunStartup = new javax.swing.JLabel();

        labelScheduleInterval.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelScheduleInterval.setText("Scheduler Interval :");

        textFieldSchedulerInterval.setText(String.valueOf(Utility.getPreference().getSchedulerTimerInterval()));
        ((AbstractDocument) textFieldSchedulerInterval.getDocument())
        .setDocumentFilter(new NumericDocumentFilter());
        textFieldSchedulerInterval.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textFieldSchedulerIntervalKeyReleased(evt);
            }
        });

        labelWebhookTimer.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelWebhookTimer.setText("Webhook Queue Delay :");

        textFieldWebhookDelay.setText(String.valueOf(Utility.getPreference().getWebhookQueueDelay()));
        ((AbstractDocument) textFieldWebhookDelay.getDocument())
        .setDocumentFilter(new NumericDocumentFilter());
        textFieldWebhookDelay.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textFieldWebhookDelayKeyReleased(evt);
            }
        });

        labelTheme.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelTheme.setText("Theme :");

        comboBoxThemes.setModel(getThemeModel());
        comboBoxThemes.addItemListener(this::comboBoxThemesItemStateChanged);

        labeFontName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labeFontName.setText("Font :");

        comboBoxFont.setModel(getFontModel());
        comboBoxFont.addItemListener(this::comboBoxFontItemStateChanged);

        labelFontSize.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelFontSize.setText("Font Size :");

        spinnerFontSize.setModel(getFontSizeModel());
        spinnerFontSize.setEditor(new javax.swing.JSpinner.NumberEditor(spinnerFontSize, ""));
        spinnerFontSize.addChangeListener(this::spinnerFontSizeStateChanged);

        buttonClose.setIcon(Utility.getCloseIcon());
        buttonClose.setText("Close");
        buttonClose.addActionListener(this::buttonCloseActionPerformed);

        checkboxRunStartup.setSelected(Utility.getPreference().isRunningAtStartup());
        checkboxRunStartup.setEnabled(StartupHelper.isWindows());
        checkboxRunStartup.addActionListener(this::checkboxRunStartupActionPerformed);

        labelRunStartup.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelRunStartup.setText("Run at Startup :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonClose)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelFontSize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(1, 1, 1))
                            .addComponent(labeFontName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelTheme, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelScheduleInterval, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelWebhookTimer, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelRunStartup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textFieldSchedulerInterval)
                    .addComponent(textFieldWebhookDelay, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(comboBoxThemes, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboBoxFont, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(spinnerFontSize, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(checkboxRunStartup, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelScheduleInterval)
                    .addComponent(textFieldSchedulerInterval, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textFieldWebhookDelay)
                    .addComponent(labelWebhookTimer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTheme)
                    .addComponent(comboBoxThemes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labeFontName)
                    .addComponent(comboBoxFont, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelFontSize)
                    .addComponent(spinnerFontSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkboxRunStartup)
                    .addComponent(labelRunStartup))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(buttonClose)
                .addGap(10, 10, 10))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {checkboxRunStartup, comboBoxFont, comboBoxThemes, labeFontName, labelFontSize, labelRunStartup, labelScheduleInterval, labelTheme, labelWebhookTimer, spinnerFontSize, textFieldSchedulerInterval, textFieldWebhookDelay});

    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxThemesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboBoxThemesItemStateChanged
        try {
            saveSettings();
        } catch (IOException | ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            DiscordFeedHubLogger.getLogger(PreferencePanel.class.getName()).log(Level.SEVERE, "Failed to save preferences", ex);
        }
    }//GEN-LAST:event_comboBoxThemesItemStateChanged

    private void comboBoxFontItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboBoxFontItemStateChanged
        try {
            saveSettings();
        } catch (IOException | ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            DiscordFeedHubLogger.getLogger(PreferencePanel.class.getName()).log(Level.SEVERE, "Failed to save preferences", ex);
        }
    }//GEN-LAST:event_comboBoxFontItemStateChanged

    private void spinnerFontSizeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerFontSizeStateChanged
        try {
            saveSettings();
        } catch (IOException | ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            DiscordFeedHubLogger.getLogger(PreferencePanel.class.getName()).log(Level.SEVERE, "Failed to save preferences", ex);
        }
    }//GEN-LAST:event_spinnerFontSizeStateChanged

    private void textFieldSchedulerIntervalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFieldSchedulerIntervalKeyReleased
        try {
            saveSettings();
        } catch (IOException | ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            DiscordFeedHubLogger.getLogger(PreferencePanel.class.getName()).log(Level.SEVERE, "Failed to save preferences", ex);
        }
    }//GEN-LAST:event_textFieldSchedulerIntervalKeyReleased

    private void textFieldWebhookDelayKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFieldWebhookDelayKeyReleased
        try {
            saveSettings();
        } catch (IOException | ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            DiscordFeedHubLogger.getLogger(PreferencePanel.class.getName()).log(Level.SEVERE, "Failed to save preferences", ex);
        }
    }//GEN-LAST:event_textFieldWebhookDelayKeyReleased

    private void checkboxRunStartupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxRunStartupActionPerformed
        try {
            saveSettings();
        } catch (IOException | ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            DiscordFeedHubLogger.getLogger(PreferencePanel.class.getName()).log(Level.SEVERE, "Failed to save preferences", ex);
        }
    }//GEN-LAST:event_checkboxRunStartupActionPerformed

    private void buttonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCloseActionPerformed
        this.closeParentDialog();
    }//GEN-LAST:event_buttonCloseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonClose;
    private javax.swing.JCheckBox checkboxRunStartup;
    private javax.swing.JComboBox<String> comboBoxFont;
    private javax.swing.JComboBox<Theme> comboBoxThemes;
    private javax.swing.JLabel labeFontName;
    private javax.swing.JLabel labelFontSize;
    private javax.swing.JLabel labelRunStartup;
    private javax.swing.JLabel labelScheduleInterval;
    private javax.swing.JLabel labelTheme;
    private javax.swing.JLabel labelWebhookTimer;
    private javax.swing.JSpinner spinnerFontSize;
    private javax.swing.JTextField textFieldSchedulerInterval;
    private javax.swing.JTextField textFieldWebhookDelay;
    // End of variables declaration//GEN-END:variables
}
