package com.junk.application.discordfeedhub.panel;

import com.junk.application.discordfeedhub.model.RssSource;
import com.junk.application.discordfeedhub.utils.DatabaseManager;
import com.junk.application.discordfeedhub.model.DmlResult;
import com.junk.application.discordfeedhub.utils.DiscordFeedHubLogger;
import com.junk.application.discordfeedhub.utils.ExtendedPanel;
import com.junk.application.discordfeedhub.utils.Utility;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author elmerhd
 */
public class ResourcePanel extends ExtendedPanel {
    
    private boolean isUpdate = false;
    private DataPanel dataPanel = null;
    private int id;
    
    public ResourcePanel(DataPanel parentDataPanel, boolean isUpdate, int id) {
        super();
        this.dataPanel = parentDataPanel;
        this.isUpdate = isUpdate;
        this.id = id;
        initComponents();
        initPlaceholders();
        setFieldValues(id);
    }
    
    @Override
    public void onInitializedPanel() {
        DiscordFeedHubLogger.getLogger(ResourcePanel.class.getName()).log(Level.INFO, "Initializing Components");
    }
    
    private void initPlaceholders() {
        String enterText = "Enter ";
        textFieldTitle.putClientProperty("JTextField.placeholderText", enterText + sanitizeLabelPlaceHolder(labelTitle));
        textFieldWebsiteUrl.putClientProperty("JTextField.placeholderText", enterText + sanitizeLabelPlaceHolder(labelWebsiteUrl));
        textFieldRssUrl.putClientProperty("JTextField.placeholderText", enterText + sanitizeLabelPlaceHolder(labelRssUrl));
        textFieldDiscordWebhook.putClientProperty("JTextField.placeholderText", enterText + sanitizeLabelPlaceHolder(labelDiscordWebhook));
        textFieldTitle.putClientProperty("JTextField.showClearButton", true);
        textFieldWebsiteUrl.putClientProperty("JTextField.showClearButton", true);
        textFieldRssUrl.putClientProperty("JTextField.showClearButton", true);
        textFieldDiscordWebhook.putClientProperty("JTextField.showClearButton", true);
    }
    
    private String sanitizeLabelPlaceHolder(JLabel label) {
        return label.getText().replaceAll(":", "").trim();
    }
    
    public void setFieldValues(int id) {
        if (isUpdate) {
            RssSource rssSource = DatabaseManager.getRssResourceById(id);
            textFieldTitle.setText(rssSource.title());
            textFieldWebsiteUrl.setText(rssSource.websiteUrl());
            textFieldRssUrl.setText(rssSource.rssUrl());
            textFieldDiscordWebhook.setText(rssSource.discordWebhookUrl());
            checkboxEnabled.setSelected(rssSource.enabled());
        }
    }
    
    private boolean isUpdate() {
        return this.isUpdate;
    }
    
    private boolean validateFieldValues() {
        return 
            !textFieldTitle.getText().isEmpty() &&
            !textFieldWebsiteUrl.getText().isEmpty() &&
            !textFieldRssUrl.getText().isEmpty() && 
            !textFieldDiscordWebhook.getText().isBlank();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonClose = new javax.swing.JButton();
        buttonSave = new javax.swing.JButton();
        labelTitle = new javax.swing.JLabel();
        textFieldTitle = new javax.swing.JTextField();
        labelWebsiteUrl = new javax.swing.JLabel();
        textFieldWebsiteUrl = new javax.swing.JTextField();
        labelRssUrl = new javax.swing.JLabel();
        textFieldRssUrl = new javax.swing.JTextField();
        labelDiscordWebhook = new javax.swing.JLabel();
        textFieldDiscordWebhook = new javax.swing.JTextField();
        labelEnabled = new javax.swing.JLabel();
        checkboxEnabled = new javax.swing.JCheckBox();

        buttonClose.setIcon(Utility.getCloseIcon());
        buttonClose.setText("Close");
        buttonClose.addActionListener(this::buttonCloseActionPerformed);

        buttonSave.setIcon(Utility.getSaveIcon());
        buttonSave.setText("Save");
        buttonSave.addActionListener(this::buttonSaveActionPerformed);

        labelTitle.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelTitle.setText("Title :");

        labelWebsiteUrl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelWebsiteUrl.setText("Website URL :");

        labelRssUrl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelRssUrl.setText("RSS URL :");

        labelDiscordWebhook.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelDiscordWebhook.setText("Discord Webhook :");

        labelEnabled.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelEnabled.setText("Enabled :");

        checkboxEnabled.setText("Enabled");
        checkboxEnabled.setEnabled(isUpdate());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(buttonSave)
                        .addGap(10, 10, 10)
                        .addComponent(buttonClose))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(labelEnabled, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                                .addComponent(labelDiscordWebhook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(labelRssUrl)
                            .addComponent(labelWebsiteUrl)
                            .addComponent(labelTitle))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textFieldTitle)
                            .addComponent(textFieldWebsiteUrl)
                            .addComponent(textFieldRssUrl)
                            .addComponent(textFieldDiscordWebhook, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(checkboxEnabled, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(10, 10, 10))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {labelDiscordWebhook, labelEnabled, labelRssUrl, labelTitle, labelWebsiteUrl});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTitle)
                    .addComponent(textFieldTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelWebsiteUrl)
                    .addComponent(textFieldWebsiteUrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRssUrl)
                    .addComponent(textFieldRssUrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDiscordWebhook)
                    .addComponent(textFieldDiscordWebhook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEnabled)
                    .addComponent(checkboxEnabled))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonClose)
                    .addComponent(buttonSave))
                .addGap(10, 10, 10))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {checkboxEnabled, labelDiscordWebhook, labelEnabled, labelRssUrl, labelTitle, labelWebsiteUrl, textFieldDiscordWebhook, textFieldRssUrl, textFieldTitle, textFieldWebsiteUrl});

    }// </editor-fold>//GEN-END:initComponents

    private void buttonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCloseActionPerformed
        this.closeParentDialog();
    }//GEN-LAST:event_buttonCloseActionPerformed

    private void buttonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaveActionPerformed
        DmlResult result = null;
        if (validateFieldValues()) {
            if (!isUpdate) {
                result = DatabaseManager.saveNewResource(textFieldTitle.getText(), textFieldWebsiteUrl.getText(), textFieldRssUrl.getText(), textFieldDiscordWebhook.getText());
            } else {
                result = DatabaseManager.updateRSSSource(id, textFieldTitle.getText(), textFieldWebsiteUrl.getText(), textFieldRssUrl.getText(), textFieldDiscordWebhook.getText(), checkboxEnabled.isSelected() ? 1 : 0);
            }
            Utility.checkStatus(this, result);
            try {
                dataPanel.loadSources();
            } catch (SQLException | IOException ex) {
                DiscordFeedHubLogger.getLogger(ResourcePanel.class.getName()).log(Level.SEVERE, (String) null, ex);
            }
        } else {
            DiscordFeedHubLogger.getLogger(PreferencePanel.class.getName()).log(Level.SEVERE, "One or More fields is required");
            JOptionPane.showMessageDialog(this, "One or More fields is required", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_buttonSaveActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonClose;
    private javax.swing.JButton buttonSave;
    private javax.swing.JCheckBox checkboxEnabled;
    private javax.swing.JLabel labelDiscordWebhook;
    private javax.swing.JLabel labelEnabled;
    private javax.swing.JLabel labelRssUrl;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JLabel labelWebsiteUrl;
    private javax.swing.JTextField textFieldDiscordWebhook;
    private javax.swing.JTextField textFieldRssUrl;
    private javax.swing.JTextField textFieldTitle;
    private javax.swing.JTextField textFieldWebsiteUrl;
    // End of variables declaration//GEN-END:variables
}
