package com.junk.application.discordfeedhub.panel;

import com.junk.application.discordfeedhub.model.RssSource;
import com.junk.application.discordfeedhub.utils.DatabaseManager;
import com.junk.application.discordfeedhub.utils.DatabaseStatementStatus;
import com.junk.application.discordfeedhub.utils.ExtendedPanelModel;
import com.junk.application.discordfeedhub.utils.Utility;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author elmerhd
 */
public class ResourcePanel extends ExtendedPanelModel {
    
    private boolean isUpdate = false;
    private DataPanel dataPanel = null;
    private int id;

    /**
     * Creates new form NewResource
     */
    public ResourcePanel(DataPanel parentDataPanel) {
        this.dataPanel = parentDataPanel;
        initComponents();
        initPlaceholders();
    }
    
    public ResourcePanel(DataPanel parentDataPanel, boolean isUpdate, int id) {
        this.dataPanel = parentDataPanel;
        this.isUpdate = isUpdate;
        this.id = id;
        initComponents();
        initPlaceholders();
        setFieldValues(id);
    }
    
    private void initPlaceholders() {
        String enterText = "Enter ";
        textTitle.putClientProperty("JTextField.placeholderText", enterText + sanitizeLabelPlaceHolder(labelTitle));
        textWebsiteUrl.putClientProperty("JTextField.placeholderText", enterText + sanitizeLabelPlaceHolder(labelWebsiteUrl));
        textRssUrl.putClientProperty("JTextField.placeholderText", enterText + sanitizeLabelPlaceHolder(labelRssUrl));
        textDiscordWebhook.putClientProperty("JTextField.placeholderText", enterText + sanitizeLabelPlaceHolder(labelDiscordWebhook));
    }
    
    private String sanitizeLabelPlaceHolder(JLabel label) {
        return label.getText().replaceAll(":", "").trim();
    }
    
    public void setFieldValues(int id) {
        RssSource rssSource = DatabaseManager.getRssResourceById(id);
        textTitle.setText(rssSource.getTitle());
        textWebsiteUrl.setText(rssSource.getWebsiteUrl());
        textRssUrl.setText(rssSource.getRssUrl());
        textDiscordWebhook.setText(rssSource.getDiscordWebhookUrl());
        checkboxEnabled.setSelected(rssSource.isEnabled());
    }
    
    private boolean isUpdate() {
        return this.isUpdate;
    }
    
    private boolean validateFieldValues() {
        return 
            !textTitle.getText().isEmpty() &&
            !textWebsiteUrl.getText().isEmpty() &&
            !textRssUrl.getText().isEmpty() && 
            !textDiscordWebhook.getText().isBlank();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonClose = new javax.swing.JButton();
        buttonSave = new javax.swing.JButton();
        labelTitle = new javax.swing.JLabel();
        textTitle = new javax.swing.JTextField();
        labelWebsiteUrl = new javax.swing.JLabel();
        textWebsiteUrl = new javax.swing.JTextField();
        labelRssUrl = new javax.swing.JLabel();
        textRssUrl = new javax.swing.JTextField();
        labelDiscordWebhook = new javax.swing.JLabel();
        textDiscordWebhook = new javax.swing.JTextField();
        labelEnabled = new javax.swing.JLabel();
        checkboxEnabled = new javax.swing.JCheckBox();

        buttonClose.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        buttonClose.setText("Close");
        buttonClose.addActionListener(this::buttonCloseActionPerformed);

        buttonSave.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        buttonSave.setText("Save");
        buttonSave.addActionListener(this::buttonSaveActionPerformed);

        labelTitle.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        labelTitle.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelTitle.setText("Title : ");

        textTitle.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        labelWebsiteUrl.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        labelWebsiteUrl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelWebsiteUrl.setText("Website URL : ");

        textWebsiteUrl.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        labelRssUrl.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        labelRssUrl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelRssUrl.setText("RSS URL : ");

        textRssUrl.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        labelDiscordWebhook.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        labelDiscordWebhook.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelDiscordWebhook.setText("Discord Webhook : ");

        textDiscordWebhook.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        labelEnabled.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        labelEnabled.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelEnabled.setText("Enabled :");
        labelEnabled.setEnabled(isUpdate());

        checkboxEnabled.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        checkboxEnabled.setText("Enabled");
        checkboxEnabled.setEnabled(isUpdate());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelEnabled, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(checkboxEnabled)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(buttonSave)
                        .addGap(10, 10, 10)
                        .addComponent(buttonClose))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelDiscordWebhook)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textDiscordWebhook, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelTitle)
                        .addGap(10, 10, 10)
                        .addComponent(textTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelWebsiteUrl)
                        .addGap(10, 10, 10)
                        .addComponent(textWebsiteUrl))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelRssUrl)
                        .addGap(10, 10, 10)
                        .addComponent(textRssUrl)))
                .addGap(10, 10, 10))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {labelDiscordWebhook, labelEnabled, labelRssUrl, labelTitle, labelWebsiteUrl});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {checkboxEnabled, textDiscordWebhook});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTitle)
                    .addComponent(textTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelWebsiteUrl)
                    .addComponent(textWebsiteUrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRssUrl)
                    .addComponent(textRssUrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDiscordWebhook)
                    .addComponent(textDiscordWebhook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEnabled)
                    .addComponent(checkboxEnabled))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonClose)
                    .addComponent(buttonSave))
                .addGap(10, 10, 10))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {checkboxEnabled, labelDiscordWebhook, labelEnabled, labelRssUrl, labelTitle, labelWebsiteUrl, textDiscordWebhook, textRssUrl, textTitle, textWebsiteUrl});

    }// </editor-fold>//GEN-END:initComponents

    private void buttonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCloseActionPerformed
        this.closeParentDialog();
    }//GEN-LAST:event_buttonCloseActionPerformed

    private void buttonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaveActionPerformed
        DatabaseStatementStatus status = null;
        if (validateFieldValues()) {
            if (!isUpdate) {
                status = DatabaseManager.saveNewResource(textTitle.getText(), textWebsiteUrl.getText(), textRssUrl.getText(), textDiscordWebhook.getText());
            } else {
                status = DatabaseManager.updateRSSSource(id, textTitle.getText(), textWebsiteUrl.getText(), textRssUrl.getText(), textDiscordWebhook.getText(), checkboxEnabled.isSelected() ? 1 : 0);
            }
            Utility.checkStatus(this, status);
            dataPanel.loadSources();
        } else {
            JOptionPane.showMessageDialog(this, "One or More fields is required", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_buttonSaveActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonClose;
    private javax.swing.JButton buttonSave;
    private javax.swing.JCheckBox checkboxEnabled;
    private javax.swing.JLabel labelDiscordWebhook;
    private javax.swing.JLabel labelEnabled;
    private javax.swing.JLabel labelRssUrl;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JLabel labelWebsiteUrl;
    private javax.swing.JTextField textDiscordWebhook;
    private javax.swing.JTextField textRssUrl;
    private javax.swing.JTextField textTitle;
    private javax.swing.JTextField textWebsiteUrl;
    // End of variables declaration//GEN-END:variables
}
