package com.junk.application.discordfeedhub.ui;

import com.junk.application.discordfeedhub.panel.DataPanel;
import com.junk.application.discordfeedhub.panel.LoadingPanel;
import com.junk.application.discordfeedhub.utils.Utility;
import java.awt.BorderLayout;
import java.io.IOException;
import java.sql.SQLException;
import java.util.Properties;

/**
 *
 * @author elmerhd
 */
public class Main extends javax.swing.JFrame {
    
    private DataPanel dataPanel = null;
    private LoadingPanel loadingPanel = null;
    /**
     * Creates new form Main
     */
    public Main() throws SQLException, IOException, Exception {
        initComponents();
        initializedPanels();
    }
    
    private String getApplicationTitle(){
            
        try {
            Properties applicationProperty = Utility.getApplicationProperty();
            String applicationName = applicationProperty.getProperty("app.name");
            return applicationName;
        } catch (IOException ex) {
            System.getLogger(Main.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            return null;
        }
    }
    
    private void initializedPanels() throws SQLException, IOException {
        dataPanel = new DataPanel(this);
        loadingPanel = new LoadingPanel(this);
        mainPanel.add(loadingPanel, BorderLayout.CENTER);
        mainPanel.revalidate();
        mainPanel.repaint();
    }
    
    public void showDataPanel() {
        mainPanel.removeAll();
        mainPanel.add(dataPanel, BorderLayout.CENTER);
        mainPanel.revalidate();
        mainPanel.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();

        setTitle(getApplicationTitle());
        setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        setIconImage(Utility.getApplicationIconImage());

        mainPanel.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 944, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
}
