package com.junk.application.discordfeedhub.ui;

import com.formdev.flatlaf.extras.components.FlatButton;
import com.junk.application.discordfeedhub.panel.AboutPanel;
import com.junk.application.discordfeedhub.panel.CheckUpdatePanel;
import com.junk.application.discordfeedhub.panel.PreferencePanel;
import com.junk.application.discordfeedhub.panel.DataPanel;
import com.junk.application.discordfeedhub.panel.LoadingPanel;
import com.junk.application.discordfeedhub.panel.LogPanel;
import com.junk.application.discordfeedhub.utils.DiscordFeedHubLogger;
import com.junk.application.discordfeedhub.utils.ExtendedDialog;
import com.junk.application.discordfeedhub.utils.Utility;
import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.io.IOException;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.util.Properties;
import java.util.logging.Level;
import javax.swing.Box;
import javax.swing.UIManager;

/**
 *
 * @author elmerhd
 */
public class Main extends javax.swing.JFrame {
    
    private DataPanel dataPanel = null;
    private LoadingPanel loadingPanel = null;
    /**
     * Creates new form Main
     */
    public Main() throws SQLException, IOException, Exception {
        initComponents();
        initializedPanels();
        setUpMenubar();
    }
    
    private String getApplicationTitle(){
        try {
            Properties applicationProperty = Utility.getApplicationProperty();
            String applicationName = applicationProperty.getProperty("app.name");
            String version = applicationProperty.getProperty("app.version");
            String template = "{0} v{1}";
            String result = MessageFormat.format(
                    template,
                    applicationName,
                    version
            );
            return result;
        } catch (IOException ex) {
            DiscordFeedHubLogger.getLogger(Main.class.getName()).log(Level.SEVERE, (String) null, ex);
            return null;
        }
    }
    
    public void setUpMenubar() {
        FlatButton settingsButton = new FlatButton();
        settingsButton.setIcon(Utility.getSettingIcon());
        settingsButton.setButtonType( FlatButton.ButtonType.toolBarButton );
        settingsButton.setFocusable( false );
        settingsButton.addActionListener((ActionEvent e) -> {
            ExtendedDialog extendedDialog = new ExtendedDialog(this, "Preferences", new PreferencePanel());
            extendedDialog.setVisible(true);
        });
        menuBarMenu.add( Box.createGlue() );
        menuBarMenu.add( settingsButton);
        UIManager.put( "MenuItem.selectionType", "underline");
    }
    
    private void initializedPanels() throws SQLException, IOException {
        dataPanel = new DataPanel(this);
        loadingPanel = new LoadingPanel(this);
        mainPanel.add(loadingPanel, BorderLayout.CENTER);
        mainPanel.revalidate();
        mainPanel.repaint();
    }
    
    public void showDataPanel() {
        mainPanel.removeAll();
        mainPanel.add(dataPanel, BorderLayout.CENTER);
        mainPanel.revalidate();
        mainPanel.repaint();
    }

    @Override
    public void setVisible(boolean b) {
        dataPanel.checkRunningScheduler();
        super.setVisible(b);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        menuBarMenu = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        menuItemClose = new javax.swing.JMenuItem();
        menuView = new javax.swing.JMenu();
        menuItemViewLogs = new javax.swing.JMenuItem();
        menuHelp = new javax.swing.JMenu();
        menuItemCheckUpdates = new javax.swing.JMenuItem();
        menuItemAbout = new javax.swing.JMenuItem();

        setTitle(getApplicationTitle());
        setIconImage(Utility.getApplicationIconImage());

        mainPanel.setLayout(new java.awt.BorderLayout());

        menuFile.setText("File");

        menuItemClose.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuItemClose.setText("Close");
        menuItemClose.addActionListener(this::menuItemCloseActionPerformed);
        menuFile.add(menuItemClose);

        menuBarMenu.add(menuFile);

        menuView.setText("View");

        menuItemViewLogs.setText("View Logs");
        menuItemViewLogs.addActionListener(this::menuItemViewLogsActionPerformed);
        menuView.add(menuItemViewLogs);

        menuBarMenu.add(menuView);

        menuHelp.setText("Help");

        menuItemCheckUpdates.setMnemonic('U');
        menuItemCheckUpdates.setText("Check for Updates");
        menuItemCheckUpdates.addActionListener(this::menuItemCheckUpdatesActionPerformed);
        menuHelp.add(menuItemCheckUpdates);

        menuItemAbout.setText("About");
        menuItemAbout.addActionListener(this::menuItemAboutActionPerformed);
        menuHelp.add(menuItemAbout);

        menuBarMenu.add(menuHelp);

        setJMenuBar(menuBarMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 944, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCloseActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_menuItemCloseActionPerformed

    private void menuItemAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAboutActionPerformed
        ExtendedDialog extendedDialog;
        extendedDialog = new ExtendedDialog(this, "About", new AboutPanel());
        extendedDialog.setVisible(true);
    }//GEN-LAST:event_menuItemAboutActionPerformed

    private void menuItemCheckUpdatesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCheckUpdatesActionPerformed
        try {
            ExtendedDialog extendedDialog = new ExtendedDialog(this, "Version Checker", new CheckUpdatePanel());
            extendedDialog.setVisible(true);
        } catch (IOException ex) {
            DiscordFeedHubLogger.getLogger(Main.class.getName()).log(Level.SEVERE, (String) null, ex);
        }
    }//GEN-LAST:event_menuItemCheckUpdatesActionPerformed

    private void menuItemViewLogsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemViewLogsActionPerformed
        ExtendedDialog extendedDialog = new ExtendedDialog(this, "Logs", new LogPanel());
        extendedDialog.setVisible(true);
    }//GEN-LAST:event_menuItemViewLogsActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel mainPanel;
    private javax.swing.JMenuBar menuBarMenu;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenu menuHelp;
    private javax.swing.JMenuItem menuItemAbout;
    private javax.swing.JMenuItem menuItemCheckUpdates;
    private javax.swing.JMenuItem menuItemClose;
    private javax.swing.JMenuItem menuItemViewLogs;
    private javax.swing.JMenu menuView;
    // End of variables declaration//GEN-END:variables
}
