name: release

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 25

      - name: Build JAR with Maven
        run: mvn -B clean package

      - name: Extract branch name
        run: |
          BRANCH_NAME=${GITHUB_REF##*/}
          TAG_NAME=v-${BRANCH_NAME}
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV

      - name: Create Git tag
        run: |
          git tag $TAG_NAME
          git push origin $TAG_NAME

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG_NAME  }}
          release_name: ${{ env.TAG_NAME  }}
          draft: false
          prerelease: false

      - name: Upload JAR to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: target/DiscordFeedHub-${{ env.TAG_NAME  }}-jar-with-dependencies.jar
          asset_name: DiscordFeedHub-${{ env.TAG_NAME  }}.jar
          asset_content_type: application/java-archive
